### ISSUE TITLE
conflict with python==3.10

### ISSUE THREAD

**Issue by candemircan** [amarquand/PCNtoolkit#107]
Hello,

There appears to be a dependency issue when following the Basic Installation instructions.

Creating an environment without specifying python version in a recent conda distribution (22.9.0) creates the environment using Python 3.10 by default. The command `conda install pip pandas scipy` runs without errors. However, when I then run `pip install pcntoolkit`, it results on the following error:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
fsleyes 1.5.0 requires pyparsing==2.*, but you have pyparsing 3.0.9 which is incompatible.
```
When I try to install the requested `pyparsing` version with `pip install pyparsing==2`, I get the following error:

```
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-5pqi43ke/pyparsing_b012152b99344c788507293b4939c673/setup.py", line 9, in <module>
          from pyparsing import __version__ as pyparsing_version
        File "/tmp/pip-install-5pqi43ke/pyparsing_b012152b99344c788507293b4939c673/pyparsing.py", line 573, in <module>
          collections.MutableMapping.register(ParseResults)
      AttributeError: module 'collections' has no attribute 'MutableMapping'
```

which I believe is caused by a change in the built-in `collection` module in Python 3.10. I did not have this issue when I used Python 3.9 or 3.8. 

## Proposed solution

Adding `python_requires='<3.10',` into the `setup` function in `setup.py` and specifying the environment creation in the docs as `conda create --name <env_name> "python<3.10"` can solve this issue for users until the dependencies change their requirements.

I was going to make a pull request, however the Sphinx version on my machine renders html slightly differently, leading to an unnecessary amount of diff lines.

Thanks,
Can

**Comment by amarquand** [comment]
Hi Can - thanks very much for pointing this out! We have added this requirement to the dev brach and we will propagate these changes also to the master branch next time we do a version release.
