### ISSUE TITLE
Syntax error in normative.py (and a fix)

### ISSUE THREAD

**Issue by jerke123** [amarquand/PCNtoolkit#113]
Hi!
I am not sure if this is a specific python version problem that does not accept this syntax, but I followed the tutorial on readthedocs which uses python 3.7.7 in a new conda environment, so I did this too.
After installing the required additional packages, trying to import pcntoolkit gave me this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../pcntoolkit/__init__.py", line 2, in <module>
    from . import normative
  File "<fstring>", line 1
    (kwargs=)
           ^
SyntaxError: invalid syntax
```

This seems to originate from line 863 in pcntoolkit/normative.py, `print(f'{kwargs=}')`. After commenting this print statement out, I can import without problems.

**Comment by jerke123** [comment]
I found in previous issues that indeed this is a syntax for python 3.8 onwards, so it might be nice to update the tutorial example of conda environment setup to use 3.8+ too

**Comment by amarquand** [comment]
Thanks Jerke -  we'll indeed update the tutorial to account for that. 
Thanks for pointing it out.
