### ISSUE TITLE
Problem when plotting centiles - AttributeError: 'NoneType' object has no attribute 'get_n_params'`

### ISSUE THREAD

**Issue by m-petersen** [amarquand/PCNtoolkit#114]
Dear Developers,

thanks for putting together PCNtoolkit. It is a great tool!

Package version: 0.27

I am trying to implement BLR with my data based on the tutorials you provide (https://github.com/predictive-clinical-neuroscience/PCNtoolkit-demo/blob/main/tutorials/BLR_protocol/BLR_normativemodel_protocol.ipynb and https://github.com/predictive-clinical-neuroscience/PCNtoolkit-demo/blob/main/tutorials/BLR_protocol/transfer_pretrained_normative_models.ipynb). 

My aim is to model a set of imaging derived phenotypes based on age and gender. Currently, I am stuck trying to plot the normative curves + centiles as described in the second tutorial (or here https://github.com/predictive-clinical-neuroscience/PCNtoolkit-demo/blob/main/tutorials/BLR_protocol/transfer_pretrained_normative_models.ipynb). The error I am getting is:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[26], line 35
     33 # get the warp and warp parameters
     34  W = nm.blr.warp
---> 35  warp_param = nm.blr.hyp[1:nm.blr.warp.get_n_params()+1] 
     37  # first, we warp predictions for the true data and compute evaluation metrics
     38  med_te = W.warp_predictions(np.squeeze(yhat_te), np.squeeze(s2_te), warp_param)[0]

AttributeError: 'NoneType' object has no attribute 'get_n_params'
```

It results form the code which tries to warp the predictions after modelling dummy data for plotting
```
    yhat, s2 = ptk.normative.predict(cov_file_dummy, 
                       alg = 'blr', 
                       respfile = None, 
                       model_path = os.path.join(roi_path,'Models'), 
                       binary=False,
                       outputsuffix = '_dummy',
                       saveoutput = True)
    
    # load the normative model
    with open(os.path.join(roi_path,'Models', 'NM_0_0_estimate.pkl'), 'rb') as handle:
        nm = pickle.load(handle) 

   # get the warp and warp parameters
    W = nm.blr.warp
    warp_param = nm.blr.hyp[1:nm.blr.warp.get_n_params()+1] 
```

The models are derived by
```
    ptk.normative.estimate(covfile = roi_train_covfile,
                        respfile = roi_train_respfile,
                        testcov = roi_test_covfile,
                        testresp = roi_test_respfile,
                        optimizer = "powell",
                        alg = "blr",
                        saveoutput = True,
                        standardize = True,
                        savemodel=True,
                        binary=True,
                        )
```

`nm.blr.warp` appears to be empty/NoneType. However `nm.blr` appears to be a proper BLR object: `nm.blr -> <pcntoolkit.model.bayesreg.BLR at 0x7faf185de820>`. Also other methods based on the warp attribute appear not to work.
```---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[24], line 38
     35 warp_param = nm.blr.hyp[1:len(nm.blr.hyp)+1] 
     37 # first, we warp predictions for the true data and compute evaluation metrics
---> 38 med_te = W.warp_predictions(np.squeeze(yhat_te), np.squeeze(s2_te), warp_param)[0]
     39 med_te = med_te[:, np.newaxis]
     40 print('metrics:', evaluate(y_te, med_te))

AttributeError: 'NoneType' object has no attribute 'warp_predictions'```

The code to estimate the model appears to work fine and I get output metrics like EV, MSLL, etc. The code is:
```    ptk.normative.estimate(covfile = roi_train_covfile,
                        respfile = roi_train_respfile,
                        testcov = roi_test_covfile,
                        testresp = roi_test_respfile,
                        optimizer = "powell",
                        alg = "blr",
                        saveoutput = True,
                        standardize = True,
                        savemodel=True,
                        binary=True,
                        )
```

You can find the Jupyter Notebook with the remaining analysis code here: https://drive.google.com/file/d/1hL6vekKTi_lEBqDzSNsYASVN9IoEfuy3/view?usp=share_link. 

Do you have any ideas what might be the issue causing the missing warp? Of course I am happy to provide further details. Thanks in advance!

Best,
Marvin

**Comment by Elleaume** [comment]
I encountered the same issue at some point. I think I solved it by adding the attributs : warp='WarpSinArcsinh', warp_reparam= True in the estimate function, not sure it's the right approach though and how to plot without warpping.

**Comment by m-petersen** [comment]
Adding "warp='WarpSinArcsinh', warp_reparam= True" to the estimate function did the trick. Thanks, Camille!

**Comment by amarquand** [comment]
Thank you for the answer Camille!
