### ISSUE TITLE
shape of the centiles

### ISSUE THREAD

**Issue by iamjoostjanssen** [amarquand/PCNtoolkit#119]
Hi,

We used the PCN-toolkit (v0.21, BLR with WarpSinArcsinh-warping and default settings (# of knots 5, order of spline 3) to model life-span right hemispheric cortical thickness for an in-house sample.

![centiles_both_k5_p3_ct](https://user-images.githubusercontent.com/24245077/234507587-ed1c2ce0-8918-4c2c-9b61-b2b4f8a5fd15.png)

The fit looks comparable to Rutherford et al. (eLife). Good. To assess the centiles we simulated a dataset for 'x' with a clear 'cylindre'-like pattern with age and sex as covariates. We then applied the PCN-toolkit (v0.21, BLR with WarpSinArcsinh-warping and default settings (# of knots 5, order of spline 3) and plotted the centiles following the published code. The centiles do not look correct.
![centiles_both_k5_p3](https://user-images.githubusercontent.com/24245077/234506869-9e3b03d6-65f3-4224-9b9a-fc37d9c490d5.png)

I'm attaching the plot and the dataset in the zip-file (age and sex distributions for train (80%) and test (20%) were kept highly similar). 
[drive-download-20230413T164029Z-001.zip](https://github.com/amarquand/PCNtoolkit/files/11330364/drive-download-20230413T164029Z-001.zip)
What are we doing wrong? Thanks!

**Comment by AuguB** [comment]
It looks like the centiles follow the data quite well, if homoskedasticity is assumed. The `varcovfile` keyword can be used to specify the covariates used for heteroskedasticity. Are you sure that you specified that keyword correctly?

https://github.com/amarquand/PCNtoolkit/blob/84e47ecb8ffa7791378c4d87a451657c416db038/pcntoolkit/normative_model/norm_blr.py#L66

**Comment by amarquand** [comment]
I think this has been addressed. Feel free to reach out via gitter if you have further questions.
