### ISSUE TITLE
Update installation information for sklearn

### ISSUE THREAD

**Issue by glick094** [amarquand/PCNtoolkit#137]
Installation instructions should be updated from `sklearn` to `scikit-learn` based on install guidelines here: https://github.com/scikit-learn/sklearn-pypi-package

Relevant lines of code:
https://github.com/amarquand/PCNtoolkit/blob/95d6eb22600f027929c5e94eade368cce0360757/README.md?plain=1#L52

**Comment by AuguB** [comment]
Thanks for submitting this issue. We have addressed this on the dev branch, and the fix will be in the upcoming release that we expect on the 15th of december
