### ISSUE TITLE
problem when using 'predict' for a HBR model

### ISSUE THREAD

**Issue by weiwei-wch** [amarquand/PCNtoolkit#138]
Hi,
I am using PCNtoolkit 0.28 to estimate a HBR normative model with health data and predict the 'yhat s2 Z' value with data (from patients) which from two sites existed in the training step, while some error occurs as follows:

`Loading data ...`
`Prediction by model  1 of 70`

`Sampling: [y_like]`

`100.00% [4000/4000 00:02<00:00]`

---------------------------------------------------------------------------
`ValueError                                Traceback (most recent call last)`
`Cell In[29], line 2`
`      1 from pcntoolkit.normative import predict`
`----> 2 yhat_new, s2_new = predict(covfile = covfile_new, `
`      3                                   alg = 'hbr', `
`      4                                   respfile = respfile_new,`
`      5                                   tsbefile = tsbefile_new,`
`      6                                   model_path = os.path.join(processing_dir,'Models'),`
`      7                                   output_path = output_path,`
`      8                                   outputsuffix = '_predictnew')`

`File ~\anaconda3\envs\nor_PCN\Lib\site-packages\pcntoolkit\normative.py:766, in predict(covfile, respfile, maskfile, **kwargs)`
`    763     yhat, s2 = nm.predict_on_new_sites(Xz, batch_effects_test)`
`    765 if outscaler == 'standardize': `
`--> 766     Yhat[:, i] = scaler_resp[fold].inverse_transform(yhat, index=i)`
`    767     S2[:, i] = s2.squeeze() * sY[fold][i]**2`
`    768 elif outscaler in ['minmax', 'robminmax']:`

`ValueError: could not broadcast input array from shape (559,) into shape (1077,)`

By the way, 559 is the size of test data I use to estimate the model, and 1077 is the size of data I need to predict, I check the size of covfile_new, respfile_new and tsbefile_new, they all have 1077 subjects

and this is the code I use for predict:

`from pcntoolkit.normative import predict`
`yhat_new, s2_new, Z_new = predict(covfile = covfile_new, `
`                                  alg = 'hbr', `
`                                  respfile = respfile_new,`
`                                  tsbefile = tsbefile_new,`
`                                  model_path = os.path.join(processing_dir,'Models'),`
`                                  output_path = output_path,`
`                                  outputsuffix = '_predictnew')`

I wanna if anyone could kindly help me out of this :)

**Comment by weiwei-wch** [comment]
> Hi Weiwei, I'm sorry to hear that you are experiencing issues. Could you make sure that you are using the most recent version of the toolkit by re-installing it? There have been some important bug fixes in the last few weeks.
> 
> Let me know if that helps.

I reinstall the toolkit last week when I start this program, it is version 0.28, is this the newest one?
and as the error happens in line 766 which is called when 'standardize' is used, I try to estimate a model without 'standardize', while the size mismatch problem still exists. Here is the error message:

`Loading data ...`
`Prediction by model  1 of 2`

`Sampling: [y_like]`

`100.00% [4000/4000 00:02<00:00]`

`---------------------------------------------------------------------------`
`ValueError                                Traceback (most recent call last)`
`Cell In[11], line 2`
`      1 from pcntoolkit.normative import predict`
`----> 2 yhat_new, s2_new, Z_new = predict(covfile = covfile_new, `
`      3                                   alg = 'hbr', `
`     4                                   respfile = respfile_new,`
`     5                                   tsbefile = tsbefile_new,`
`      6                                   model_path = os.path.join(processing_dir,'Models'),`
`      7                                   output_path = output_path,`
`      8                                   outputsuffix = '_predictnew')`

`File ~\anaconda3\envs\nor_PCN\Lib\site-packages\pcntoolkit\normative.py:772, in predict(covfile, respfile, maskfile, **kwargs)`
`    770         S2[:, i] = s2 * (scaler_resp[fold].max[i] - scaler_resp[fold].min[i])**2`
`    771     else:`
`--> 772         Yhat[:, i] = yhat.squeeze()`
`   773         S2[:, i] = s2.squeeze()`
`    775 if respfile is None:`

`ValueError: could not broadcast input array from shape (559,) into shape (1077,)`

**Comment by amarquand** [comment]
Hi - please make sure you download the latest version from github. We have not updated PyPI yet (i.e. the pip repository). Then you will be sure to get the updates that Stijn is mentioning above.

**Comment by weiwei-wch** [comment]
Hi - I reinstall the latest version from github, while the same problem still occur

> Hi - please make sure you download the latest version from github. We have not updated PyPI yet (i.e. the pip repository). Then you will be sure to get the updates that Stijn is mentioning above.

**Comment by likeajumprope** [comment]
Hi @weiwei-wch, thank  you for bringing this up - we have dug deeper and  discovered a problem in the toolbox. We will let you know once its fixed!

**Comment by gourdchen** [comment]
I have the same problem! Whatever I input, the output dimension will become the same as the train data (such as I train the model with 500 samples, the output will be "could not broadcast input array from shape (500,) into shape (myinput.shape[0],)" ).  Would you please help me fix this problem?

**Comment by AuguB** [comment]
@likeajumprope Is this problem fixed in the upcoming release?

**Comment by likeajumprope** [comment]
No I don't think so

**Comment by AuguB** [comment]
okay, then I will assign it to myself and have a look next week
