### ISSUE TITLE
Predict function: UnboundLocalError: local variable 'nm' referenced before assignment

### ISSUE THREAD

**Issue by LuRoe7** [amarquand/PCNtoolkit#139]
I train a normative model using the following function (2 folds just for testing purposes):

estimate(respfile=os.path.join(input_dir,"train_resp.txt"),
         covfile=os.path.join(input_dir,"train_cov.txt"),
         testresp=os.path.join(input_dir,"test_resp.txt"),
         testcov=os.path.join(input_dir,"test_cov.txt"),
         cvfolds=2,
         alg="blr",
         optimizer = "powell",
         outputsuffix= "_2fold",
         saveoutput=True,
         savemodel=True,
         standardize = True)

Then I want to apply the model to the test data:

predict(covfile=os.path.join(input_dir,"test_cov.txt"),
        respfile=os.path.join(input_dir,"test_resp.txt"),
        model_path=os.path.join(proc_dir,"Models"),
        alg="blr",
        outputsuffix="_test",
        return_y=True )

I get the following error:

UnboundLocalError                         Traceback (most recent call last)
Cell In[36], line 1
----> 1 predict(covfile=os.path.join(input_dir,"test_cov_dm.txt"),
      2         respfile=os.path.join(input_dir,"test_resp.txt"),
      3         model_path=os.path.join(proc_dir,"Models"),
      4         alg="blr",
      5         outputsuffix="_test",
      6         return_y=True
      7        )
File ~/anaconda3/lib/python3.8/site-packages/pcntoolkit/normative.py:799, in predict(covfile, respfile, maskfile, **kwargs)
    796     Y = Y[:, np.newaxis]
    798 # warp the targets?   
--> 799 if alg == 'blr' and nm.blr.warp is not None:
    800     warp = True
    801     Yw = np.zeros_like(Y)            

UnboundLocalError: local variable 'nm' referenced before assignment

Any ideas?

Thanks!

**Comment by LuRoe7** [comment]
It is the same file. I did not specify the predict command correctly here. It was:

predict(covfile=os.path.join(input_dir,"test_cov_dm.txt"),
respfile=os.path.join(input_dir,"test_resp.txt"),
model_path=os.path.join(proc_dir,"Models"),
alg="blr",
outputsuffix="_test",
return_y=True )

All text files are formatted according to the requirements specified in your documentation...

**Comment by likeajumprope** [comment]
Ah I think the problem is that you need to change the "outputsuffix" in the predict part to "inputsuffix". Otherwise the predict function cannot find the model. Can you try that? 

Alternatively you can leave all the suffixes out (both in estimate and predict), then the models and all the output will just be tagged with the default words "estimate" and "predict". The predict function should then be able to find the model automatically based on that.

**Comment by LuRoe7** [comment]
Yes that was the reason! Thank you!

Would be good to add a more detailed documentation of the estimate and predict function on your homepage. I didn't even know that one can specify the "inputsuffix" argument since it is not mentioned in the docs: https://amarquand.github.io/PCNtoolkit/doc/build/html/pages/modindex.html#normative.predict. Maybe one could include a detailed explanation of every argument of the central functions of your package?

But anyway, great package that facilitates our work here

**Comment by likeajumprope** [comment]
Hi @LuRoe7 great that it worked in the end!

And thank you for the feedback, we will definitively consider updating the docs regarding this point!
