### ISSUE TITLE
Testing Demo Notebooks - HBR Fcon

### ISSUE THREAD

**Issue by likeajumprope** [amarquand/PCNtoolkit#155]

**Comment by likeajumprope** [comment]
Transfer to new sites gives the following error:

<img width="820" alt="image" src="https://github.com/amarquand/PCNtoolkit/assets/23728822/37e09e20-fd4a-4b39-8de5-be387db1e166">

**Comment by AuguB** [comment]
I can not reproduce this error, are we using the same version of the toolkit? `pip list` gives me:?
![Screenshot from 2023-12-13 14-38-01](https://github.com/amarquand/PCNtoolkit/assets/19709783/8aec46dc-5d70-4c80-a7fe-0d245c310938)

**Comment by AuguB** [comment]
My transfer runs successfully:

![Screenshot from 2023-12-13 14-39-31](https://github.com/amarquand/PCNtoolkit/assets/19709783/8e491f16-a9ec-48bd-b92e-97fa7224f433)

**Comment by likeajumprope** [comment]
I have pandas version 1.5.3...

**Comment by likeajumprope** [comment]
Now it works! Treating this as solved.
