### ISSUE TITLE
Testing Demo Notebooks - HBR SHASH

### ISSUE THREAD

**Issue by likeajumprope** [amarquand/PCNtoolkit#156]

**Comment by likeajumprope** [comment]
When generating the QQ plots I get the following error:
<img width="820" alt="image" src="https://github.com/amarquand/PCNtoolkit/assets/23728822/5ab373e7-ac39-4aae-b58c-5641b381de39">

**Comment by AuguB** [comment]
Try changing it to `nm.get_mcmc_zscores(X_test_standardized, Y_test_standardized, tsbefile = Z_test.astype(int))

**Comment by likeajumprope** [comment]
tried that but I still gives an error

**Comment by likeajumprope** [comment]
Done and all dependencies removed.
