### ISSUE TITLE
question regarding normative trajectory GPR

### ISSUE THREAD

**Issue by HSweatman** [amarquand/PCNtoolkit#201]
Hello, 

I am following the GPR tutorial to model a few different measures of functional connectivity with age as a covariate. I was expecting the normative trajectory to be linear or a curve as in the tutorial, but for one of my features, I am getting a jagged line (the rest appear linear). Does this suggest there is something wrong with my model? Attaching an image of the jagged one and a linear one for comparison. 
<img width="575" alt="DorsalAttention_SS" src="https://github.com/amarquand/PCNtoolkit/assets/72632764/79cf17b9-54f2-4d72-a3ff-6accdd75c2d5">
<img width="553" alt="Visual_SS" src="https://github.com/amarquand/PCNtoolkit/assets/72632764/a94c0bac-de57-4367-8474-bbb5576f1a84">

For reference, the feature being modelled is system segregation of the 7 Yeo networks ([functional connectivity within - between system] / functional connectivity within system). 
 
Thank you!

**Comment by amarquand** [comment]
HI - yes, there is definitely something wrong. You might like to first check the visualisation steps and check that the grid you are using to plot the fitted models is not too coarse. It could also be that the estimated lengthscale is quite short

**Comment by HSweatman** [comment]
Hi, thanks for your reply! I followed the tutorial closely for visualization (sample of my modified code below in case) and also tried at a finer grained scale (13 points instead of 7) - the issue persists for that specific model (both male and female trajectories), while the 11 other trajectories look linear. The input data looks comparable to the other models as well.
When you say the estimated lengthscale, are you referring to the age range?

```
import numpy as np
import matplotlib.pyplot as plt
import math

#### make list of ages rounded down for CI calculation
x = covariate_normsample.values
xround=[]
for num in range(0,103):
    temp=[math.floor(x[num,1])]
    xround=xround+temp
xround=np.array(xround)
#### confidence interval calculation at x_forward
def confidence_interval(s2,x,z):
  CI=np.zeros((len(x_forward),12)) # 12 times for different features
  for i,xdot in enumerate(x_forward):
        ci_inx=np.isin(xround,xdot)
        S2=s2[ci_inx]
        S_hat=np.mean(S2,axis=0)
        n=S2.shape[0]
        CI[i,:]=z*np.power(S_hat/n,.5)
  return CI

feature_names=['FC_mean','FC_variance','Visual_SS','Somatomotor_SS','DorsalAttention_SS','Salience_SS','Limbic_SS','Control_SS','Default_SS','FCw_mean','FCb_mean','SS_mean']
sex_covariates=['Male','Female']
for i,sex in enumerate(sex_covariates):
   #### forward model data
    forward_yhat = pd.read_csv('yhat_forward.txt', sep = ' ', header=None)
    yhat_forward=forward_yhat.values
    yhat_forward=yhat_forward[7*i:7*(i+1)]
    x_forward=[6, 10, 14, 18, 22, 26, 30]
    
    ####  Find the index of the data exclusively for one sex. Female:1, Male: 0   
    inx=np.where(covariate_normsample.sex==i)[0]
    x=xround[inx]

    ####  actual data
    y = pd.read_csv('features_normsample.txt', sep = ' ', header=None)
    y = y.values[inx]
 

    ####  confidence Interval yhat+ z *(std/n^.5)-->.95 % CI:z=1.96, 99% CI:z=2.58
    s2= pd.read_csv('ys2_5fold.txt', sep = ' ', header=None)
    s2=s2.values

    CI_95=confidence_interval(s2,xround,1.96)
    CI_99=confidence_interval(s2,xround,2.58)
    
    ####  Creat a trajectory for each point
    for j,name in enumerate(feature_names):

        fig=plt.figure()
        ax=fig.add_subplot(111)
        ax.plot(x_forward,yhat_forward[:,j], linewidth=4, label='Norm trajectory')


        ax.plot(x_forward,CI_95[:,j]+yhat_forward[:,j], linewidth=2,linestyle='--',c='g', label='95% CI')
        ax.plot(x_forward,-CI_95[:,j]+yhat_forward[:,j], linewidth=2,linestyle='--',c='g')

        ax.plot(x_forward,CI_99[:,j]+yhat_forward[:,j], linewidth=1,linestyle='--',c='k', label='99% CI')
        ax.plot(x_forward,-CI_99[:,j]+yhat_forward[:,j], linewidth=1,linestyle='--',c='k')

        ax.scatter(x,y[:,j],c='r', label=name)
        plt.legend(loc='lower left')
        plt.title('Normative trajectory of ' +name+' in '+sex+' cohort')
        plt.show()
        plt.close()
```

**Comment by amarquand** [comment]
Hi - it is because you have only  7 steps in your input vector, so it is just interpolating between them, i.e. the line:

x_forward=[6, 10, 14, 18, 22, 26, 30]

If you make that more fine grained the curve will be smoother.
