### ISSUE TITLE
A problem with scipy version

### ISSUE THREAD

**Issue by wangzhe73** [amarquand/PCNtoolkit#206]

**Comment by wangzhe73** [comment]
Thank you for these great resources!
When I was installing pcntoolkit in my virtual environment with Python==3.9, scipy==1.13, an error message poped up that    "ImportError: cannot import name 'gaussian' from 'scipy.signal'".
After changing the scipy version into 1.12.0, the installation process finished with no bugs. Maybe scipy change the scipy.signal.gaussian to scipy.signal.window.gaussian?

**Comment by amarquand** [comment]
Thanks for that. Yes, we noticed that as well. I think they scipy developers changed their API in the newest release. We will update the requirements in the next release, but for now if you downgrade your scipy version it will work as a work-around

**Comment by amarquand** [comment]
We updated the requirements for the latest release.
