### ISSUE TITLE
Installation requires Theano>=1.0.5

### ISSUE THREAD

**Issue by jflournoy** [amarquand/PCNtoolkit#34]
I got the following error after running `python3 setup.py install`:

```
Installed /users/jflournoy/.conda/envs/normative_modeling/lib/python3.8/site-packages/Theano-1.0.4-py3.8.egg
error: Theano 1.0.4 is installed but theano>=1.0.5 is required by {'pymc3'}
```

Changing the version required in the setup.cfg solved the issue, I think.

**Comment by amarquand** [comment]
Thanks for pointing this out. this has been fixed.
