### ISSUE TITLE
error in importing theano

### ISSUE THREAD

**Issue by alegiac95** [amarquand/PCNtoolkit#44]
Hi, when i import theano i get the following error: `ImportError: cannot import name 'is_same_graph' from 'theano.gof.toolbox'`. I tried also re-installing theano from scratch but still can't fix this issue. Does it depend from the theano installation or somehing else?

**Comment by amarquand** [comment]
Hi - that looks like a theano error to me. Could you please try using a different version of theano? I am using Theano v 1.0.5 without any problems and it works
