### ISSUE TITLE
Theano-PyMC version mismatch

### ISSUE THREAD

**Issue by sunhuaiqiang** [amarquand/PCNtoolkit#49]
I installed pcntookit via pip, when I excute 'import pcntoolkit as pcn', it returns following errors.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
The installed Theano(-PyMC) version (1.0.5) does not match the PyMC3 requirements.
For PyMC3 to work, Theano must be uninstalled and replaced with Theano-PyMC.
See https://github.com/pymc-devs/pymc3/wiki for installation instructions.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I tried to uninstall Theano and re-install Theano-PyMC, but it did not work. looking forward to your help

**Comment by smkia** [comment]
Which PyMC3 version is installed in your environment?

**Comment by sunhuaiqiang** [comment]
Downgrade PyMC3 to 3.8 fix the issue, and arviz also should be downgraded to 0.11.0
