### ISSUE TITLE
Add FAQ page

### ISSUE THREAD

**Issue by saigerutherford** [amarquand/PCNtoolkit#58]
The documentation also has an empty page currently for Frequently Asked Questions (FAQ). We should brainstorm what questions are typically asked by new users and fill in this page (docs/source/pages/FAQ.rst) accordingly.

**Comment by AmandaWorker** [comment]
**Installation of PCNToolkit 0.18**

If you are seeing errors relating to theano when you import the necessary packages to run the PCNToolkit, there may be a conflict between theano and theano-pymc3 in your environment. As a workaround for the issue try the below installation procedure.

![image](https://user-images.githubusercontent.com/32248180/123851191-d0c2d400-d912-11eb-855c-b27943ac1024.png)

The main difference here is that you are specifying the versions for arviz and pymc3, which prevents theano-pymc3 from being installed with the pcntoolkit installation.
