### ISSUE TITLE
Confusions about optimization outputs 

### ISSUE THREAD

**Issue by LINCiii** [amarquand/PCNtoolkit#64]
While using the PCNtoolkit for a GPR regression, the scipy.optimize.fmin_cg() function printed results as below:
![image](https://user-images.githubusercontent.com/87136810/124940983-036c7b00-e03d-11eb-8167-7228aaa274ec.png)
This optimal function takes "log p(y|X)" as input, so on my comprehension theoretically the "current function value"  should be around zero; It seems like after hyperparameter-optimization process, the "Current function value" is still so high? Is that normal / correct? ; As I used the codes and demo data offered on GitHub (from https://github.com/saigerutherford/PCNtoolkit-demo), I couldn't figure out which part goes wrong and hope you could answer my confusions.

**Comment by amarquand** [comment]
Hi - actually the quantity that is minimized is the *negative* log marginal likelihood, so the values you report are within a reasonable range. Note that while the log likelihood is usually negative, it can also be positive (e.g. if the underlying distribution is sharply peaked - see https://blog.stata.com/2011/02/16/positive-log-likelihood-values-happen/)
