### ISSUE TITLE
Errors: No module named 'nm_utils'

### ISSUE THREAD

**Issue by bsjeong** [amarquand/PCNtoolkit#69]
Dear PCNtoolkit developer,

Thank you for providing incredible tools!
I am following 'braincharts' tutorial.

When the following command applied in Colab,
   from nm_utils import remove_bad_subjects, load_2d

the error comes up like below: 
   ModuleNotFoundError: No module named 'nm_utils'

Best regards,

Jeong

**Comment by amarquand** [comment]
Hi - that is not part of the core repository. It is part of the supplementary routines supplied in the braincharts repository (https://github.com/predictive-clinical-neuroscience/braincharts). You need to make sure that it is findable by python (e.g. adding it to the path
