### ISSUE TITLE
Link to Saige's tutorial in the readme is dead

### ISSUE THREAD

**Issue by AuguB** [amarquand/PCNtoolkit#75]
The link on this page: https://pcntoolkit.readthedocs.io/en/latest/pages/tutorial_HBR.html 
points to: https://github.com/predictive-clinical-neuroscience/PCNtoolkit-demo/blob/main/tutorials/ROI_blr_cortthick/NormativeModelTutorial.ipynb
but I believe it should point to: https://github.com/predictive-clinical-neuroscience/PCNtoolkit-demo/blob/main/tutorials/HBR_FCON/HBR_NormativeModel_FCONdata_Tutorial.ipynb

**Comment by saigerutherford** [comment]
The link is actually correct, but the reason for it pointing to another tutorial was not clear. I have clarified why we include the BLR tutorial link in the HBR tutorial (because the BLR tutorial includes a section on formatting the data and this section is not included in the HBR tutorial)
