### ISSUE TITLE
Error in running the predict function

### ISSUE THREAD

**Issue by alegiac95** [amarquand/PCNtoolkit#77]
Hi, 
after having estimated a normative model I'm encountering an error in the `predict` function. 
The error I get is the following:
```python
Loading data ...
Prediction by model  1 of 998575
Error: No module named 'bayesreg'
Traceback (most recent call last):
File "fdopa_prediction.py", line 47, in <module>
    alg="blr")
File "/home/k19080168/norm_modelling/lib/python3.7/site-packages/pcntoolkit/normative.py", line 718, in predict
    str(i) + inputsuffix + '.pkl'))
File "/home/k19080168/norm_modelling/lib/python3.7/site-packages/pcntoolkit/normative_model/norm_base.py", line 56, in load
    nm = pickle.load(handle)
ModuleNotFoundError: No module named 'bayesreg'
```

I've checked also the imports and the `bayesreg` model should be imported correctly from the library. Is there something I'm missing?

**Comment by amarquand** [comment]
Hi - it is hard to debug with this level of detail (i.e. I don't know actually what kind of model you are fitting). But it seems like either your installation has not been performed correctly (i.e. it can't find a module that is part of the distribution), or you are using scripts that were written for a different version of the toolbox (e.g. the tutorials). We refactored the code around version 0.19 or so, so you will need to update your imports if you just cut and paste from some of the tutorials.
