### ISSUE TITLE
New published version (0.24) bugs

### ISSUE THREAD

**Issue by alegiac95** [amarquand/PCNtoolkit#87]
Hi @amarquand, 
I've tried the new version of the pcntoolkit you've published and I have found a bug in the HBR.
In particular, when I run it the code gives me a `KeyError` at `line 453` of the `normative.py` script.

I had a look and from what I saw in your code there is a point where there is a `y_like` variable passed to one of the dictionaries but none of the declared dictionaries in the HBR have a key called `y_like` which causes the issue and crashes the estimation.

In addition to this I have a question about the number `predict` function of the `normative.py` script. In particular my question is this: if i run the predict function on a new cohort with an already estimated model, will the estimation not be based on just a subset of the training set? I ask this because the `fold` parameter is set to 0, if not provided, which corresponds to the first run of the CV, which should not contain all data in the training set. Am I wrong in assuming this?

**Comment by amarquand** [comment]
Hi - thanks for pointing this out. We will look into it. 

Regarding the predict, actually I would recommend to avoid cross-validation if you can. Specifying fold=0 will use only the first fold. If you want to retrain the model using all the data, then you will need to do it manually.

**Comment by AuguB** [comment]
Hi,

I have pushed a new version on dev, could you try that one? 

Also, could you send me a snippet of your call to the function in normative.py?

**Comment by alegiac95** [comment]
Hi, 

I've tried the new version and it works without any issues so far.

Anyway the call to the `normative.py` function is:

```python 
estimate(covfile=fixed_train, 
	respfile=respfile, 
	maskfile=maskfile, 
	trbefile=random_train,
	alg="hbr", 
	optimizer="powell",
        cvfolds=5,
	saveoutput=True,
        savemodel=True,
        outputsuffix="_hbr_phno")

```
Nothing too fancy there.

**Comment by AuguB** [comment]
Great!

The issue was in the hbr.py transform_X function, which should return a Phi based on X. It only had cases defined for when a basis expansion was selected, and not for the case where there wasn't. I now added that last case:

 `def transform_X(self, X):
        if self.model_type == 'polynomial':
            Phi = create_poly_basis(X, self.configs['order'])
        elif self.model_type == 'bspline':
            if self.bsp is None:
                self.bsp = bspline_fit(X, self.configs['order'], self.configs['nknots'])
            bspline = bspline_transform(X, self.bsp)
            Phi = np.concatenate((X, bspline), axis = 1)
        else:
            Phi = np.copy(X)
        return Phi
`
