### ISSUE TITLE
GPR-model  predict problem

### ISSUE THREAD

**Issue by kkaiwang07** [amarquand/PCNtoolkit#96]
First, I use this ‘savemodel ’method to save the GPR model, for example, 
pcn.normal.estimate (covfile = '. / data / covariable_normsample. TXT', respfile = '. / data / features_normsample. TXT', cvfolders = 2, alg = 'GPR', savemodel = true)

Then I used predict to test the new data set, and the following problems occurred:

783 nm = nm.load(os.path.join(modelpath, 'NM' + str(fold) + '_' +

784 str(m) + inputsuffix + '.pkl'))

785 if (alg!='hbr' or nm.configs['transferred']==False):

--> 786 yhat, s2 = nm. predict(Xz, **kwargs)

787 else:

788 tsbefile = kwargs.get('tsbefile')

ypeError: predict() missing 2 required positional arguments: 'X' and 'y'.

I checked the source code and found that the GPR model must pass XS, X and Y parameters to predict, but this code only passed in one parameter: yhat, S2 = nm Predict (XZ, * * kwarg), so I think there is a problem in this place. I hope it can be solved. Thanks

**Comment by kkaiwang07** [comment]
prediction code:
hat_te, s2_te, Z = predict(cov_file_te, 
                                    alg='gpr', 
                                    respfile=resp_file_te, 
                                    model_path=model_path)
error info:
File ~/opt/anaconda3/lib/python3.9/site-packages/pcntoolkit/normative.py:797, in predict(covfile, respfile, maskfile, **kwargs)
    793 # nm = nm.load(os.path.join(model_path, 'NM_' + str(fold) + '_' +
    794 #                           str(m) + '_2fold.pkl'))
    795 if (alg!='hbr' or nm.configs['transferred']==False):
--> 797     yhat, s2 = nm.predict(Xz,**kwargs)
    798     print('----yhat, s2 = nm.predict(Xz, **kwargs)----',yhat, s2)
    799 else:

TypeError: predict() missing 2 required positional arguments: 'X' and 'y'

**Comment by amarquand** [comment]
Hi - actually we do not support predict() for the GPR models. This is because GPR requires access to the training data at test time (to compute the cross covariance matrix). Unlike the other methods, we cannot just supply it with a set of parameters. We will put in a check in a future version to catch this. If you want to make predictions using the GPR models, it needs to be done with estimate().
