### ISSUE TITLE
Interpretation of CI in GPR model

### ISSUE THREAD

**Issue by arokem** [amarquand/PCNtoolkit#97]
Hello! First of all, thanks for creating these wonderful tools.

I have what may be more of a conceptual question related to the interpretation of the confidence intervals produced by the software rather than to the technical implementation. But please bear with me. 

Here it is: In the [GPR example](https://pcntoolkit.readthedocs.io/en/latest/pages/normative_modelling_walkthrough.html) there are about 650 participants that are being analyzed. When producing 99% CIs, I would have expected to have about 1% of the subjects outside of these bounds, but in the figures that are produced in the example, there are clearly more than 7 participants that are outside of the CI in each of the ROIs that are displayed. What does that mean? Is my expectation of 1% participants outside of the 99% CI misplaced? Are these bounds somehow smaller than I would have expected, or need some kind of correction to simultaneously cover the full range (a la [this for GAMs](https://fromthebottomoftheheap.net/2016/12/15/simultaneous-interval-revisited/))?

Thanks in advance for any thoughts you have about this!

**Comment by amarquand** [comment]
Hi - there are several reasons why the posterior predictive intervals might not match the empirical data. The most important is that the predictions are derived out of sample (i.e. on independent data). Therefore any kind of dataset shift or difference between training and test data may influence the proportion of samples that fall outside a given centiles. Also any non-Gaussianity or heteroskedasticity might mean that the expected centiles don't match the true data. See Fraza et al 2021 NIMG for more thoughts about this
